name: Continuous Integration
on:
  push:
  pull_request:
    types: [opened, reopened]
    branches: "feature/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and Start Containers
        run: |
          docker-compose up -d --build

          
      - name: Stop and Remove Containers
        run: |
          docker-compose down
