name: Continuous Integration
on:
  push:
  pull_request:
    types: [opened, reopened]
    branches: "feature/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Update and Upgrade Ubuntu Packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Docker and Docker Compose  # Adicionado o hífen faltante
        run: |
          sudo apt-get update
          sudo apt-get install --only-upgrade -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '\"tag_name\": \"\K(.*)(?=\")')" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Start Containers
        run: |
          docker-compose up --build

      - name: Stop and Remove Containers
        run: |
          docker-compose down
